# Generated by Django 6.0.3 on 2026-03-16 22:08

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(upload_to=documents.models.file_upload_path),
        ),
    ]
