# Generated by Django 6.0.3 on 2026-03-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_path',
            new_name='file',
        ),
    ]
