# Generated by Django 6.0.3 on 2026-03-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_file_path_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
    ]
