# Generated by Django 6.0.3 on 2026-03-25 20:54

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_document_file_size_remove_document_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to=documents.models.file_upload_path),
        ),
    ]
