# Generated by Django 6.0.3 on 2026-03-31 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_difficulty_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='generationconfig',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='generationconfig',
            name='number_of_mcqs',
        ),
        migrations.RemoveField(
            model_name='generationconfig',
            name='temperature',
        ),
        migrations.AddField(
            model_name='generationconfig',
            name='temp',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='generationconfig',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='number_of_mcqs',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='generation_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quizzes.generationconfig'),
        ),
        migrations.AddField(
            model_name='generationconfig',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_configs', to='quizzes.llmmodel'),
        ),
    ]
