# Generated by Django 6.0.3 on 2026-03-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_llmmodel_remove_generationconfig_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='generation_config',
        ),
    ]
