# Generated by Django 6.0.3 on 2026-04-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='total_questions',
        ),
    ]
